Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerScienceTsu.Models.Generated;
using System.IO;
using ComputerScienceTsu.Services;

namespace ComputerScienceTsu.Controllers
{
    public class NewsController : Controller
    {
        private TsuModel db = new TsuModel();

        // GET: News
        public ActionResult Index()
        {
            var news = db.News.Include(n => n.User);
            return View(news.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            ViewBag.Created_by = new SelectList(db.Users, "ID", "Username");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Title, string Content, int Created_by, HttpPostedFileBase file)
        {
            string alternativePath = @"/Content/images/" + file.FileName;
            file.SaveAs(Path.Combine(Server.MapPath("~/Content/images"), file.FileName));
            var news = NewsService.SetNews(Title, Content, Created_by, alternativePath);
            news.Created_at = DateTime.Now;
            news.Updated_at = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.Created_by = new SelectList(db.Users, "ID", "Username", news.Created_by);
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Content,Created_by,Created_at,Updated_at")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Created_by = new SelectList(db.Users, "ID", "Username", news.Created_by);
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserController.cs
using ComputerScienceTsu.Models.Generated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerScienceTsu.Services;
using System.Web.Security;

namespace ComputerScienceTsu.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Registration(string firstname, string lastname, string username, string email, string pass)
        {
            bool emailExists = UserService.EmailExists(email);

            if (!emailExists)
            {
                var user = UserService.SetUser(firstname, lastname, username, email, UserService.Hash(pass));
                using (TsuModel db = new TsuModel())
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return View("RegistrationSuccessful");
                }
            }

            return View();
        }

        [HttpPost]

        public ActionResult Login(string email, string pass, string remember)
        {
            using (TsuModel db = new TsuModel())
            {
                var user = db.Users.Where(e => e.Email == email).FirstOrDefault();
                if (user != null)
                {
                    if (string.Compare(UserService.Hash(pass), user.Pass) == 0)
                    {
                        var RememberChecked = remember == "on" ? true : false;
                        int timeout = RememberChecked ? 525600 : 20;
                        var ticket = new FormsAuthenticationTicket(email, RememberChecked, timeout);
                        string encrypted = FormsAuthentication.Encrypt(ticket);
                        var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                        cookie.Expires = DateTime.Now.AddMinutes(timeout);
                        cookie.HttpOnly = true;
                        Response.Cookies.Add(cookie);
                        Session["UserID"] = user.ID.ToString();
                        Session["Username"] = user.Username;
                        return View("LoginSuccessful");
                    }

                    else
                        ModelState.AddModelError("LoginError", "Username or password is wrong.");
                   }
                else
                {
                    ModelState.AddModelError("LoginError", "Username or password is wrong.");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            Session.Remove("Username");
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }


    }
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="ka">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Computer Science Department Site">
    <meta name="author" content="Students">

    <!-- fb -->
    <meta property="og:image" content="" />
    <meta property="og:description" content="" />

    <!--twitter-->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="">
    <meta name="twitter:description" content="">
    <meta name="twitter:image" content="">

    <link type="image/x-icon" rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="~/Content/stylesheets/map.css">

    <title>TSU კომპიუტერული მეცნიერება</title>
</head>
<body>


    <div style="position:absolute;" id="user-form" class="login-form-wrap">
        <div class="user-form-bg user-close-toggle"></div>
        <div class="login-container-table">
            <div class="login-container-col">
                <form class="login-form" action="@Url.Action("Login", "User")" method="POST">
                    <h2>შესვლა</h2>
                    <div class="form-group has-icon">
                        <input type="email" name="email" placeholder="ელ. ფოსტა" class="form-control">
                        <span class="form-icon"><i class="fa fa-user"></i></span>
                    </div>
                    <div class="form-group has-icon">
                        <input type="password" name="pass" placeholder="პაროლი" class="form-control">
                        <span class="form-icon"><i class="fa fa-lock"></i></span>
                    </div>
                    <div class="checkbox clearfix">
                        <div class="pull-left">
                            <label>
                                <input type="checkbox" name="remember"> დამიმახსოვრე
                            </label>
                        </div>
                        <div class="pull-right text-right">
                            <a href="#">დაგავიწყდა პაროლი?</a>
                        </div>
                    </div>
                    <div class="clearfix">
                        <div class="pull-left register-btn"><a href="@Url.Action("Registration", "User")"><i class="fa fa-user-plus"></i>&nbsp;რეგისტრაცია</a></div>
                        <div class="pull-right"><input type="submit" class="btn btn-primary" value="შესვლა"></div>
                    </div>
                    <span class="login-close-btn user-close-toggle"><i class="fa fa-close"></i></span>
                </form>
            </div>
        </div>
    </div>

    <!-- Start Header -->
    <header class="header">
        <nav class="navbar navbar-custom">
            <div class="container">
                <div class="navbar-left">
                    <a class="navbar-logo clearfix" href="@Url.Action("Index", "Home")">
                        <img src="~/Content/images/cs-logo.png">
                        <h4 class="hidden-sm hidden-xs">ივანე ჯავახიშვილის სახელობის<br>თბილისის სახელმწიფო უნივერსიტეტი</h4>
                    </a>
                </div>

                <div class="navbar-right navbar-icons">

                    @{
                        if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("Logout", "User", FormMethod.Post, new { id = "logoutForm" }))
                            {
                            <a style="color:red;" href="javascript:document.getElementById('logoutForm').submit()">ანგარიშიდან გასვლა</a>
                            }
                        }
                        else {
                                 <div class="navbar-icon user-btn user-btn-toggle">
                                 <i class="fa fa-user fa-2x"></i>
                                </div>
                                <div class="navbar-icon btn-menu-toggle">
                                    <i class="fa fa-bars fa-2x"></i>
                                </div>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>

    <aside id="aside" class="aside">
        <nav>
            <ul class="aside-menu">
                <li class="aside-menu-item"><a href="#">მთავარი</a></li>
                <li class="aside-menu-item"><a href="@Url.Action("Index","News")">სიახლეები</a></li>
                <li class="aside-menu-item has-submenu">
                    <a>ჩვენ შესახებ&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                    <ul class="aside-submenu">
                        <li class="aside-submenu-item"><a href="#">ისტორია</a></li>
                        <li class="aside-submenu-item"><a href="#">კათედრების სია</a></li>
                        <li class="aside-submenu-item"><a href="#">აკადემიური პერსონალი</a></li>
                        <li class="aside-submenu-item"><a href="#">ლაბორატორიები</a></li>
                        <li class="aside-submenu-item"><a href="#">ინსტიტუტები</a></li>
                        <li class="aside-submenu-item"><a href="#">საერთაშორისო ვიზიტები</a></li>
                    </ul>
                </li>
                <li class="aside-menu-item has-submenu">
                    <a>სწავლება&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                    <ul class="aside-submenu">
                        <li class="aside-submenu-item"><a href="#">საბაკალავრო პროგრამები</a></li>
                        <li class="aside-submenu-item"><a href="#">სამაგისტრო პროგრამები</a></li>
                        <li class="aside-submenu-item"><a href="#">სადოქტორო პროგრამები</a></li>
                        <li class="aside-submenu-item"><a href="#">სასწავლო/საწარმოო პრაქტიკა</a></li>
                    </ul>
                </li>
                <li class="aside-menu-item has-submenu">
                    <a>კვლევა&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                    <ul class="aside-submenu">
                        <li class="aside-submenu-item"><a href="#">კვლევის მიმართულებები</a></li>
                        <li class="aside-submenu-item"><a href="#">კონფერენციები</a></li>
                        <li class="aside-submenu-item"><a href="#">გრანტები</a></li>
                        <li class="aside-submenu-item"><a href="#">ექსპედიციები</a></li>
                        <li class="aside-submenu-item"><a href="#">დაცული დისერტაციები</a></li>
                        <li class="aside-submenu-item"><a href="#">მიმდინარე მიზნობრივი პროექტები</a></li>
                        <li class="aside-submenu-item"><a href="#">სტუდენტთა სამეცნიერო წრე</a></li>
                    </ul>
                </li>
                <li class="aside-menu-item"><a href="gallery.html">ფოტოგალერეა</a></li>
                <li class="aside-menu-item"><a href="#">კონტაქტი</a></li>
            </ul>
        </nav>
    </aside>


    <div class="container body-content">
        @RenderBody()

            <footer class="footer">
                <div class="container">
                    <div class="footer-widgets">
                        <div class="row">

                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <h3 class="widget-title">ჩვენ შესახებ</h3>
                                <ul>
                                    <li><a href="#">ისტორია</a></li>
                                    <li><a href="#">კათედრების სია</a></li>
                                    <li><a href="#">აკადემიური პერსონალი</a></li>
                                    <li><a href="#">ლაბორატორიები</a></li>
                                    <li><a href="#">ინსტიტუტები</a></li>
                                    <li><a href="#">საერთაშორისო ვიზიტები</a></li>
                                </ul>
                            </div>

                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <h3 class="widget-title">სწავლება</h3>
                                <ul>
                                    <li><a href="#">საბაკალავრო პროგრამები</a></li>
                                    <li><a href="#">სამაგისტრო პროგრამები</a></li>
                                    <li><a href="#">სადოქტორო პროგრამები</a></li>
                                    <li><a href="#">სასწავლო/საწარმოო პრაქტიკა</a></li>
                                </ul>
                            </div>

                            <div class="clear-sm"></div>

                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <h3 class="widget-title">კვლევა</h3>
                                <ul>
                                    <li><a href="#">კვლევის მიმართულებები</a></li>
                                    <li><a href="#">კონფერენციები</a></li>
                                    <li><a href="#">გრანტები</a></li>
                                    <li><a href="#">ექსპედიციები</a></li>
                                    <li><a href="#">დაცული დისერტაციები</a></li>
                                    <li><a href="#">მიმდინარე მიზნობრივი პროექტები</a></li>
                                    <li><a href="#">სტუდენტთა სამეცნიერო წრე</a></li>
                                </ul>
                            </div>


                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <h3 class="widget-title">გამოცემები</h3>
                                <ul>
                                    <li><a href="#">პერიოდული გამოცემა</a></li>
                                    <li><a href="#">მონოგრაფიები</a></li>
                                    <li><a href="#">სახემძღვანელოები</a></li>
                                    <li><a href="#">პრეპრინტები</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="footer-bottom">

                        <div class="footer-media">
                            <a href="#" class="f-facebook"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="f-twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="f-google"><i class="fa fa-google-plus"></i></a>
                            <a href="#" class="f-youtube"><i class="fa fa fa-youtube-play"></i></a>
                            <a href="#" class="f-plus"><i class="fa fa-plus"></i></a>
                        </div>

                        <div class="copyright">
                            <p>თბილისის სახელმწიფო უნივერსიტეტი &copy; 2016</p>
                        </div>

                    </div>
                </div>
            </footer>
        </div>
        </section>

        
         Scripts go here, let the page load faster 
        <script src="~/Scripts/jquery.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/fancybox-mousewheel.js"></script>
        <script src="~/Scripts/fancybox.js"></script>
        <script src="~/Scripts/scripts.js"></script>
</body>
</html>