Models/Generated/Lecturer.cs
namespace ComputerScienceTsu.Models.Generated
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Lecturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecturer()
        {
            Publications = new HashSet<Publication>();
            Subjects = new HashSet<Subject>();
        }

        public int ID { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(50)]
        public string Lastname { get; set; }

        [StringLength(30)]
        public string Phone { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(2500)]
        public string About { get; set; }

        [StringLength(2500)]
        public string Additional_info { get; set; }

        public int? Photo_id { get; set; }

        public int? Cathedra_ID { get; set; }

        [Required]
        [StringLength(2500)]
        public string Full_address { get; set; }

        public virtual Photo Photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_Departments> CS_Departments { get; set; }
    }
}

Controllers/LecturersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerScienceTsu.Models.Generated;
using ComputerScienceTsu.Services;
using System.IO;

namespace ComputerScienceTsu.Views
{
    public class LecturersController : Controller
    {
        private TsuModel db = new TsuModel();

        // GET: Lecturers
        public ActionResult Index()
        {
            var lecturers = db.Lecturers.Include(l => l.Photo);
            return View(lecturers.ToList());
        }

        // GET: Lecturers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecturer lecturer = db.Lecturers.Find(id);
            if (lecturer == null)
            {
                return HttpNotFound();
            }
            return View(lecturer);
        }

        // GET: Lecturers/Create
        public ActionResult Create()
        {
            ViewBag.Photo_id = new SelectList(db.Photos, "ID", "Image_path");
            return View();
        }

        // POST: Lecturers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Name, string Lastname, string Phone, string Email, string About, string Additional_info, string Full_address, HttpPostedFileBase file)
        {
            string alternativePath = @"/Content/images/" + file.FileName;
            var photo = LecturersService.SetPhoto(alternativePath);
            file.SaveAs(Path.Combine(Server.MapPath("~/Content/images"), file.FileName));
            if (photo != null)
            {
                db.Photos.Add(photo);
                db.SaveChanges();
            }

            var lecturer = LecturersService.SetLecturer(Name, Lastname, Phone, Email, About, Additional_info, photo.ID, Full_address);

            if (ModelState.IsValid)
            {
                db.Lecturers.Add(lecturer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Photo_id = new SelectList(db.Photos, "ID", "Image_path", lecturer.Photo_id);
            return View(lecturer);
        }

        // GET: Lecturers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecturer lecturer = db.Lecturers.Find(id);
            if (lecturer == null)
            {
                return HttpNotFound();
            }
            ViewBag.Photo_id = new SelectList(db.Photos, "ID", "Image_path", lecturer.Photo_id);
            return View(lecturer);
        }

        // POST: Lecturers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Lastname,Phone,Email,About,Additional_info,Photo_id,Full_address")] Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lecturer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Photo_id = new SelectList(db.Photos, "ID", "Image_path", lecturer.Photo_id);
            return View(lecturer);
        }

        // GET: Lecturers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecturer lecturer = db.Lecturers.Find(id);
            if (lecturer == null)
            {
                return HttpNotFound();
            }
            return View(lecturer);
        }

        // POST: Lecturers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lecturer lecturer = db.Lecturers.Find(id);
            db.Lecturers.Remove(lecturer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Lecturers/Create.cshtml
@model ComputerScienceTsu.Models.Generated.Lecturer


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Lecturers", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    <h4>Lecturer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "სახელი" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control", placeholder = "გვარი" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "ტელეფონი" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "მეილი" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control", placeholder = "ლექტორის შესახებ" } })
            @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Additional_info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Additional_info, new { htmlAttributes = new { @class = "form-control", placeholder = "დამატებითი ინფორმაცია" } })
                @Html.ValidationMessageFor(model => model.Additional_info, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Additional_info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cathedra_ID, Model.CS_Departments )
                @Html.ValidationMessageFor(model => model.Additional_info, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Photo_id, "Photo", htmlAttributes: new { @class = "control-label col-md-2", placeholder = "სურათი" })
        <div class="col-md-10">
            <input type="file" name="file" value="Browse" class="form-control"/>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Full_address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Full_address, new { htmlAttributes = new { @class = "form-control", placeholder = "უნივერსიტეტი, ქალაქი, ქუჩა, კორპუსი, დეპარტამენტი" } })
            @Html.ValidationMessageFor(model => model.Full_address, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Lecturers/Delete.cshtml
@model ComputerScienceTsu.Models.Generated.Lecturer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lecturer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Photo.Image_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo.Image_path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.About)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Additional_info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Additional_info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Full_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Lecturers/Details.cshtml
@model ComputerScienceTsu.Models.Generated.Lecturer

<section id="news">
    <div class="container">
        <div class="content">
            <div class="row">
                <div class="col-lg-3 col-md-4 bottom-sm">
                    <nav class="box-white no-padding">
                        <ul class="side-menu">
                            <li class="sidemenu-item"><a href="#">სიახლეები</a></li>
                            <li class="sidemenu-item has-dropdown">
                                <a>კათედრების სია&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                                <ul class="side-submenu">
                                    <li class="submenu-item"><a href="#">გამოყენებითი ინფორმატიკა</a></li>
                                    <li class="submenu-item"><a href="#">თეორიული ინფორმატიკა</a></li>
                                    <li class="submenu-item"><a href="#">პრაქტიკული ინფორმატიკა</a></li>
                                    <li class="submenu-item"><a href="#">ტექნიკური ინფორმატიკა</a></li>
                                </ul>
                            </li>
                            <li class="sidemenu-item"><a href="#">ლაბორატორიები</a></li>
                            <li class="sidemenu-item"><a href="#">ინსტიტუტები</a></li>
                            <li class="sidemenu-item has-dropdown">
                                <a>სწავლება&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                                <ul class="side-submenu">
                                    <li class="submenu-item"><a href="#">საბაკალავრო პროგრამები</a></li>
                                    <li class="submenu-item"><a href="#">სამაგისტრო პროგრამები</a></li>
                                    <li class="submenu-item"><a href="#">სადოქტორო პროგრამები</a></li>
                                    <li class="submenu-item"><a href="#">სასწავლო/საწარმოო პრაქტიკა</a></li>
                                </ul>
                            </li>
                            <li class="sidemenu-item has-dropdown">
                                <a>კვლევა&nbsp;&nbsp;<i class="fa fa-caret-down"></i></a>
                                <ul class="side-submenu">
                                    <li class="submenu-item"><a href="#">კვლევის მიმართულებები</a></li>
                                    <li class="submenu-item"><a href="#">კონფერენციები</a></li>
                                    <li class="submenu-item"><a href="#">გრანტები</a></li>
                                    <li class="submenu-item"><a href="#">ექსპედიციები</a></li>
                                    <li class="submenu-item"><a href="#">დაცული დისერტაციები</a></li>
                                    <li class="submenu-item"><a href="#">მიმდინარე მიზნობრივი პროექტები</a></li>
                                    <li class="submenu-item"><a href="#">სტუდენტთა სამეცნიერო წრე</a></li>
                                </ul>
                            </li>
                            <li class="sidemenu-item"><a href="">ფოტოგალერეა</a></li>
                            <li class="sidemenu-item"><a href="">კონტაქტი</a></li>
                        </ul>
                    </nav>
                </div>


                <div class="col-lg-6 col-md-8">
                    <div class="box-white">

                        <div class="lecturer-inf clearfix">

                            <div class="lecturer-avatar">
                                <img src="@Html.DisplayFor(model => model.Photo.Image_path)" class="img-thumbnail">
                            </div>

                            <h2 class="lecturer-name">@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Lastname)</h2>
                            <h4 class="lecturer-profession">ასოცირებული პროფესორი</h4>

                            <ul class="lecturer-list">
                                <li><i class="fa fa-home"></i>&nbsp;@Html.DisplayFor(model => model.Full_address)</li>
                                <li style="text-align:right;"> <i class="fa fa-phone"></i>&nbsp;@Html.DisplayFor(model => model.Phone)</li>
                                <li style="text-align:right;"><i class="fa fa-envelope-o"></i>&nbsp;<a href="mailto:@Html.DisplayFor(model => model.Email)">@Html.DisplayFor(model => model.Email)</a></li>
                            </ul>

                        </div>

                        <div id="tabs">

                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">კურსები</a></li>
                                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">პუბლიციები</a></li>
                                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">დამატებითი ინფო</a></li>
                                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">@Html.DisplayFor(model => model.Name)-ს შესახებ</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="home">
                                    <div class="tab-content">
                                    </div>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="profile">
                                    @foreach (var item in Model.Publications)
                                    {
                                        <p style="margin-left:2%;"><a href="/Publications/Details/@item.ID">@item.Title</a></p>
                                    }

                                </div>
                                <div role="tabpanel" class="tab-pane" id="messages">@Html.DisplayFor(model => model.Additional_info)</div>
                                <div role="tabpanel" class="tab-pane" id="settings">@Html.DisplayFor(model => model.About)</div>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="col-lg-3 hidden-sm hidden-xs hidden-md">
                    <div class="box-white sidebar-hotlinks">

                        <a href="http://tsu.edu.ge/ge/faculties/science/ojyqp0d9tyfxg2m/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/abi.jpg" alt="">
                        </a>

                        <a href="http://tsu.edu.ge/ge/faculties/science/yoqrmvp_gctzkw9mk/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/sandiego-uni.png" alt="">
                        </a>

                        <a href="https://www.tsu.ge/ge/faculties/science/gcxwjek_yvqyft0g4/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/geo-german.png" alt="">
                        </a>

                        <a href="https://www.tsu.ge/ge/faculties/science/aybwuvm7mmpi70j9o/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/baneri-STM.png" alt="">
                        </a>

                        <a href="https://www.tsu.ge/ge/faculties/science/iglb0tdf6hhohskx/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/projects-1.png" alt="">
                        </a>

                        <a href="https://www.tsu.ge/ge/faculties/science/_wfplofnpxmqm4qwr/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/banner-viktorina.png" alt="">
                        </a>

                        <a href="http://www.ffi.tsu.ge/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/ffi.gif" alt="">
                        </a>

                        <a href="https://www.tsu.ge/ge/faculties/science/jqvn8ssyelvp0-lyn/">
                            <img class="img-responsive" src="https://www.tsu.ge/data/image_db_innova/faculty_zust/gacvliTi.jpg" alt="">
                        </a>

                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Lecturers/Edit.cshtml
@model ComputerScienceTsu.Models.Generated.Lecturer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lecturer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Additional_info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Additional_info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Additional_info, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Full_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Lecturers/Index.cshtml
@model IEnumerable<ComputerScienceTsu.Models.Generated.Lecturer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.About)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Additional_info)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Full_address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.About)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Additional_info)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Full_address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>